require("user.options")
require("user.plugins")
require("user.colourscheme")
require("user.treesitter")
require("user.completion")
require("user.lsp")
require("user.telescope")
require("user.tags")
require("user.comments")
require("user.lualine")
require("user.undotree")
require("user.brackets")
require("user.git")
require("user.snippets")
require("user.tree")
require("user.utils.trevj")
require("user.utils.template-string")

vim.cmd("source ~/.config/nvim/vim/tex.vim")
