return {
  ["Attribute"] = true,
  ["Component"] = true,
  ["ContentChild"] = true,
  ["ContentChildren"] = true,
  ["Directive"] = true,
  ["Host"] = true,
  ["HostBinding"] = true,
  ["HostListener"] = true,
  ["Inject"] = true,
  ["Injectable"] = true,
  ["Input"] = true,
  ["NgModule"] = true,
  ["Optional"] = true,
  ["Output"] = true,
  ["Pipe"] = true,
  ["Self"] = true,
  ["SkipSelf"] = true,
  ["ViewChild"] = true,
  ["ViewChildren"] = true,
}
